modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "vinery"
version = "${version}"
displayName = "Vinery"
authors = "satisfy_u, Cristelknight, BaumeisterJO(weird name but a nice guy)"
description = '''
Vinery contains nearly everything needed for not only creating wine but also for building up your own vinery.
'''
logoFile = "assets/vinery/icon.png"

[[dependencies.vinery]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "NONE"
side = "BOTH"